### ISSUE TITLE
historical data lightweight values

### ISSUE THREAD

**Issue by apcode** [liampauling/betfair#148]
Hi, I'm using a script similar to examples/examplestreaminghistorical.py
I have set lightweight=True when constructing the listener.

In one market book sent to HistoricalStream.on_process() I'm surprised to see multiple entries for each runner in the market_book list. It looks like the availableToBack and availableToLay are sent in separate dicts even for the same runner.

Is this expected? I thought the cache should coalesce these.

E.g. this section has four entries for selectionId 13443274

'runners': [{'adjustmentFactor': 3.39,
              'ex': {'availableToBack': [],
                     'availableToLay': [],
                     'tradedVolume': []},
              'handicap': 0,
              'lastPriceTraded': None,
              'removalDate': None,
              'selectionId': 13443274,
              'sp': {'actualSP': None,
                     'backStakeTaken': [],
                     'farPrice': None,
                     'layLiabilityTaken': [{'price': 1.01, 'size': 4.95}],
                     'nearPrice': None},
              'status': u'ACTIVE',
              'totalMatched': None},
             {'adjustmentFactor': 3.39,
              'ex': {'availableToBack': [{'price': 10.5, 'size': 15.08},
                                         {'price': 10, 'size': 29.55},
                                         {'price': 9.2, 'size': 3.72},
                                         {'price': 9, 'size': 112.94},
                                         {'price': 8, 'size': 129.07},
                                         {'price': 7, 'size': 150.59},
                                         {'price': 2, 'size': 25},
                                         {'price': 1.03, 'size': 478.1},
                                         {'price': 1.02, 'size': 20},
                                         {'price': 1.01, 'size': 155.21}],
                     'availableToLay': [],
                     'tradedVolume': []},
              'handicap': 0,
              'lastPriceTraded': None,
              'removalDate': None,
              'selectionId': 13443274,
              'sp': {'actualSP': None,
                     'backStakeTaken': [],
                     'farPrice': None,
                     'layLiabilityTaken': [],
                     'nearPrice': None},
              'status': u'ACTIVE',
              'totalMatched': None},
             {'adjustmentFactor': 3.39,
              'ex': {'availableToBack': [],
                     'availableToLay': [{'price': 20, 'size': 2.95},
                                        {'price': 24, 'size': 2.95},
                                        {'price': 34, 'size': 32.31},
                                        {'price': 44, 'size': 24.8},
                                        {'price': 55, 'size': 0.82},
                                        {'price': 60, 'size': 18.07},
                                        {'price': 100, 'size': 2.07},
                                        {'price': 200, 'size': 0.07},
                                        {'price': 1000, 'size': 4.64}],
                     'tradedVolume': []},
              'handicap': 0,
              'lastPriceTraded': None,
              'removalDate': None,
              'selectionId': 13443274,
              'sp': {'actualSP': None,
                     'backStakeTaken': [],
                     'farPrice': None,
                     'layLiabilityTaken': [],
                     'nearPrice': None},
              'status': u'ACTIVE',
              'totalMatched': None},
             {'adjustmentFactor': 3.39,
              'ex': {'availableToBack': [],
                     'availableToLay': [],
                     'tradedVolume': []},
              'handicap': 0,
              'lastPriceTraded': None,
              'removalDate': None,
              'selectionId': 13443274,
              'sp': {'actualSP': None,
                     'backStakeTaken': [],
                     'farPrice': 1.0,
                     'layLiabilityTaken': [],
                     'nearPrice': 10.5},
              'status': u'ACTIVE',
              'totalMatched': None},

**Comment by liampauling** [comment]
Got a marketId? I think I have seen this before and is due to Betfair, what version of lightweight are you using?

**Comment by apcode** [comment]
lightweight version 1.5.9
marketId 1.132561952

Interestingly that was the first randomly selected market I tried. I haven't found the same in a few other  markets I've looked at. Maybe it is just betfair's data.
