### ISSUE TITLE
MarketDefinition doesn't handle missing openDate field

### ISSUE THREAD

**Issue by agberk** [liampauling/betfair#157]
Experienced the following error when dealing with a marketDefinition field in the streaming API which doesn't have an openDate field:

```
  File "/venv/lib/python3.5/site-packages/betfairlightweight/resources/streamingresources.py", line 289, in __init__
    'marketDefinition' in kwargs else None
TypeError: __init__() missing 1 required positional argument: 'openDate'
```

Pretty much the same thing as https://github.com/liampauling/betfair/issues/97

Although the marketDefinition is mentioned in the stream API [documentation](http://docs.developer.betfair.com/docs/display/1smk3cen4v3lu3yomq5qye0ni/Exchange+Stream+API) it doesn't actually list what fields it's supposed to have and following on from that which ones are supposedly required. Looking at the Swagger schema [here](https://github.com/betfair/stream-api-sample-code/blob/master/ESASwaggerSchema.json) it doesn't seem to say whether fields are required or not, though I only gave it a cursory glance. Perhaps that means there's an implicit assumption that all of them are optional?

However, even in the cases when they're explicitly listed as required by the Betfair API documentation, we still run into cases where the fields are missing: https://github.com/liampauling/betfair/issues/95

The solution for this particular instance is to just make the openDate field a kwarg and ensure the value gets set appropriately depending on whether it's supplied or not.

However the overarching problem is still there that if any other fields are missed out (and presumably whatever the error is on Betfair's end means that it would be possible for other ones to be missed) a similar issue will occur in the future.

I think required fields on resources should be positional/required args and not including them (whether it's because they didn't come through from Betfair or not) should result in an error.

Not sure how viable or enticing my suggestion is but if the cache operated on just json/dicts then it could be more robust. That could either extend the existing lightweight option or be another option. From what I can see the lightweight option will send MarketBooks as json but the underlying cache is still operating on resources.

The alternative is to make all fields which aren't listed as required in the docs kwargs.

Perhaps this discussion should go into a separate issue?

PR incoming for this.

**Comment by liampauling** [comment]
> I think required fields on resources should be positional/required args and not including them (whether it's because they didn't come through from Betfair or not) should result in an error.

Did you mean to write ‘not result in an error’? Or catch the error and raise a lightweight exception?

I see what you mean about the cache, storing the definition as a dict and only converting if required is a simple fix but it doesn’t help people who don’t use the lightweight option. It’s tricky and I really don’t like how the addition of fields from Betfair can result in everything breaking.

**Comment by agberk** [comment]
I did mean that it should raise an error :smile: if the documentation says that it's a required field then if it doesn't have the field it's an invalid representation of the object, and part of the point of having a class with explicit fields is to provide some safeguard that you don't have invalid representations flying around (otherwise you'd just use data, i.e. JSON/dicts). Not really sure how the best error handling would work.

I think the required changes are opaque to whether you're using the lightweight option or not; it looks like all the changes would be to MarketBookCache - all the fields which are currently resources would become dicts and the logic to update them changed to replacing keys; the create_resource method would then have some extra work to do in creating the resources for the fields of the MarketBook which themselves were resources. You're just changing the place where the resources are created. I was just about to say of course that doesn't help you if you're not using the lightweight option as a missing field will still cause an Exception, which is what you said so I guess we're on the same page!

Are you averse to making all of the fields kwargs then? If so, why?

**Comment by liampauling** [comment]
Averse only from a purist, if its wrong; error point of view as you have mentioned but then if a market is missing a field for its lifetime it will error every time. As you mentioned it will still cause an exception but then we can catch it one place which I like.

I was thinking about separating streamingresources out into:

- streaming/cache.py
- resources/streamingresources.py

 And then focus on refactoring cache so that it doesn't use any resources till serialisation, thoughts?

**Comment by agberk** [comment]
Sounds like a good approach to me - the cache did seem a bit out of place containing the logic for processing updates etc., while the rest of that module is just the resource definitions.

So you would wrap the resource creation in try/except so that it wouldn't have any uncaught exceptions whether the lightweight option was turned on or not?

**Comment by liampauling** [comment]
Yeh so:

`python
try:
    serialise = self. serialise
except Catch:
    raise LightweightError?

if lightweight:
    return self.serialise
else:
    return MarketBook(
    )
`

This means Stream._process (maybe Stream.snap as well) will have to catch that error and maybe log a error? This would prevent the entire stream going down but I am not sure if its the right thing to do.

**Comment by liampauling** [comment]
I have made an initial stab but limited to just refactoring to separate cache/resources, looks like a lot has changed but it actually only involved a few changes with it making things much simpler.

https://github.com/liampauling/betfair/pull/162
