### ISSUE TITLE
Permission error when streaming historical data

### ISSUE THREAD

**Issue by kauto23** [liampauling/betfair#161]
Having downloaded files using the instructions in examplehistoricdata.py, when following examplestreaminghistorical.py to stream the data files I'm receiving the following error:

`PermissionError: [Errno 13] Permission denied: '/Users/parkinm/python'`

Both directory in trading.streaming.create_historical_stream() and store_directory in trading.historic.download_file() now point towards the directory above.

I'm able to read/write other files in this directory using Python, so I'm not sure why I'm being given this error. Is there something I could be overlooking here thats causing me it?

**Comment by liampauling** [comment]
Looks like you are trying to save in your python directory, do you want to do this?

**Comment by liampauling** [comment]
Sorry missed this, which line is giving the error?

**Comment by liampauling** [comment]
It’s because you are trying to open the directory rather than a file, change to ‘C:/pythontemp/MARKET_ID’, files have to be processed one at a time.
