### ISSUE TITLE
list_event_types OverflowError: Maximum recursion level reached

### ISSUE THREAD

**Issue by varneyo** [liampauling/betfair#175]
Hi I have recently installed the betfair library and I have tried to run one of the examples, exampleone.py and run into a "OverflowError: Maximum recursion level reached" error at line 12 of the script.

Not to sure what is causing this. Is anyone else having the same issue ?

**Comment by varneyo** [comment]
Looking into this further I am pretty sure that market_filter in filters.py is called multiple times when imported and the args =locals() is causing recursion, changing the dict size to include all the parameters then another key called args with again all the parameters and so on recursively. i.e. simplified example
args = {text_query:'Football', event_type_ids=None,........args:{text_query:'Football', event_type_ids=None......, args: .....}}.

I am new to python but this looks strange to me and I can get the code to work when I replace the args = locals() line with a dictionary ({text_query:'Football'}).

Any help would be greatly appreciated.

**Comment by liampauling** [comment]
Are you using VSCode?

From the slack group a few months ago:

> Morning all - minor update re the recursion issue I was having with vscode last week, confirmed as an issue : https://github.com/Microsoft/vscode-python/issues/581

**Comment by varneyo** [comment]
I am using visual studios 2017. I have built this outside visual studio and have got it running without any issues but I would still like to get it running is VS as it has many useful development features. I have asked for help in that thread so I will see if I can get it to work.

**Comment by jamesmundy** [comment]
I recently stumbled across this problem also using VS Code, the issue only occurred in debug mode. I reported the issue to Microsoft: https://github.com/microsoft/ptvsd/issues/1417#issuecomment-491953433

They've come back with a reference to another issue where the reason this is happening is explained: https://github.com/microsoft/ptvsd/issues/1265#issuecomment-476807912

They suggest that if a static version of `locals()` is required then it is better to write `locals().copy()`. I've made this change in a local copy of the library wherever `locals()` is used which has fixed the issue. It might be worth considering the change as VS Code is increasingly popular and they aren't sure if anything can be done to fix the debugger (https://github.com/microsoft/ptvsd/issues/1417#issuecomment-491953433)?

**Comment by liampauling** [comment]
The fact that vscode is doing something so hacky that it impacts using a normal python object such as locals is deeply worrying. 

Sorry but not really willing to join them in this style of programming by doing something hacky ourselves like copy (works fine in PyCharm).

**Comment by jamesmundy** [comment]
Fair comment @liampauling - I've mentioned to them that the same code was working fine before a recent update I made so hopefully it is just something they have broken and can fix when they look into it. Thanks for your work on the library!

**Comment by fabioz** [comment]
@liampauling 

Note that you don't need to do a copy, you can simply inline the call... I'm sure that PyCharm would break too if you step into that function or get the locals from that stack after the first call to `locals()` (any call to get the `locals()` -- or `frame.f_locals` -- which is how the debugger gets the variables would break). 

The breakage is very dependent on the place where the debugger is stopped or where the user steps.

i.e.: 
```
def check():
    local1 = 10
    frame_locals = locals()
    locals()  # if this is done (which would be expected by a debugger), `frame_locals` appears in itself.
    print(sorted(frame_locals.keys()))
    
check()
    
```

Note that the debuggers from PyCharm, PyDev and VSCode all have the same backend (they're all based on https://github.com/fabioz/PyDev.Debugger/).

**Comment by liampauling** [comment]
@fabioz thanks for your input, I can't replicate this as its my understanding our use of 'clean_locals' is basically a copy as we create a new dictionary.

https://github.com/liampauling/betfair/blob/master/betfairlightweight/utils.py#L20

**Comment by fabioz** [comment]
If the parent frame `locals()` is called inside the `clean_locals()` method, it'd have a version with an additional `args` which wouldn't work (unless you filtered it out)... 

Also, it doesn't seem like `clean_locals()` is used in https://github.com/liampauling/betfair/blob/master/betfairlightweight/filters.py#L94.

The problem is that Python by design makes `locals()` and `frame.f_locals` always return the same underlying dictionary and every access to it updates it again (thus changing any reference to it) -- having the debugger work with it or not depends a lot on the place you stop and the info that's collected by the debugger.
