### ISSUE TITLE
Unable to install-Visual C++ 14.0 dependency

### ISSUE THREAD

**Issue by royshubhajit** [liampauling/betfair#184]
I am trying to install betfairlightweight but it seems to have some dependency on Visual C++ 14.0
I have the latest Visual studio installed and the link provided in the Error description does not work.
Please help.
I have python version 3.6.5
The error is as follows:
    running install
    running build
    running build_ext
    building 'ciso8601' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by liampauling** [comment]
I assume this is on a windows machine? 

bflw doesn't actually need ciso8601 so you can try a pip install ignore ciso8601 (google how) and see if it works.
