### ISSUE TITLE
CertsError: Certificate folder not found in /certs/

### ISSUE THREAD

**Issue by pdivos** [liampauling/betfair#185]
most likely I am missing something fundamental here but since I assume a lot of other people would be in the same situation I thought it would make sense to address this.

I did copy my cert file client-2048.pem in the folder /certs which I do verify before calling login, however I am still getting

> Exception: Certificate folder not found in /certs/

Here is my repro, I used Python 3.6:

```
import os
assert 'client-2048.pem' in os.listdir('/certs/')
import betfairlightweight
trading = betfairlightweight.APIClient('username', 'password', app_key='api_key')
trading.login()
```

I think it would be helpful to either clarify in the README.md the exact list of flles that need to be copied to the /certs folder and/or update the exception message because in the above situation it's misleading: the '/certs/' folder does exist while the exception message claims it doesn't.

**Comment by liampauling** [comment]
Require .crt and .key file for login, welcome PR for exception clarification.

https://github.com/liampauling/betfair/blob/master/betfairlightweight/baseclient.py#L139

**Comment by pdivos** [comment]
cheers man!

**Comment by patsess** [comment]
Thanks for all your work on betfairlightweight Liam.

I have my .crt file in my /certs/ folder, and I have an app key from BetFair. Could you specify how to get the app key into the expected .key file please? Do I create a file and paste it in (if so what is the expected format and file name)? Or do I get the file from somewhere (e.g. can I download it from BetFair somehow)?

Am I right in thinking that if I get the .key file correct then I don't need to do the exports suggested in the link that you to pdivos (above)?

Thank you in advance.

**Comment by liampauling** [comment]
Not sure what you are trying to do here? Have you read the docs?

**Comment by pdivos** [comment]
This is what I followed:

You need to copy the .crt and .key file in the /certs/ folder.

**Comment by pdivos** [comment]
I added the link to README, here is my pull request:
https://github.com/liampauling/betfair/compare/master...pdivos:patch-1

**Comment by patsess** [comment]
That's brilliant, found my .key file using this. Thanks both
