### ISSUE TITLE
Add support for sort order and max results to market filter

### ISSUE THREAD

**Issue by rorycurtis** [liampauling/betfair#188]
Add sort and max_results parameters to filters.market_filter(), so they can be sent to list_events.

I currently create the filter manually and then pass it to trading.betting.list_events ...

filter = {..."sort": sort_order, "maxResults": max_results}
trading.betting.list_events(filter=filter ...)

but it would be much clearer to use the filters.market_filter() API.

**Comment by liampauling** [comment]
I am looking at the docs and it states that listEvents uses the normal market filter or are the docs wrong?

https://docs.developer.betfair.com/plugins/servlet/mobile?contentId=3833932#content/view/3833928

**Comment by rorycurtis** [comment]
You're right @liampauling. The docs suggest that sort and maxResults aren't used in list_events. I have been using them and they appear to be working but best to ignore that and just stick to what is officially supported.

This can be closed.
