### ISSUE TITLE
Exception : ConnectionError

### ISSUE THREAD

**Issue by csaiedu** [liampauling/betfair#190]
Upon using the example 1 of the package I get regular exception when trying to load say 50 markets in `    market_catalogues = trading.betting.list_market_catalogue(

        filter=filters.market_filter(

            event_type_ids=[horse_racing_id],  # filter on just horse racing

            market_countries=['GB'],  # filter on just GB countries

            market_type_codes=['WIN'],  # filter on just WIN market types

        ),

        market_projection=['MARKET_START_TIME', 'RUNNER_DESCRIPTION'],  # runner description required

        max_results=50

    )
`
It works fine for 1 to 5 markets. The API I currently use is the test API, so may be it's beyond the ability of the test API to return more than a certain number of markets?

APIError: SportsAPING/v1.0/listMarketBook 
Params: {'priceProjection': {'rolloverStakes': False, 'virtualise': True, 'exBestOffersOverrides': {}, 'priceData': ['EX_BEST_OFFERS']}, 'marketIds': ['1.146560116']} 
Exception: ConnectionError

Thanks

**Comment by liampauling** [comment]
I don’t believe there are any limits on the delayed key reagarding max results so I assume this is your internet connection.
