### ISSUE TITLE
Streaming with delayed key?

### ISSUE THREAD

**Issue by xgshark** [liampauling/betfair#194]
I can use APIClient.trading.betting.list_* with my delayed key and the certs I made.

When I attempt the socket example displayed on the github startpage I get the error message:
"betfairlightweight.exceptions.SocketError: Connection closed by server".

When I run the examplestreaming.py from the /examples folder I get the error:
"betfairlightweight.exceptions.ListenerError: connection_id:..., data: {"op":"status","id":2,"statusCode":"FAILURE","errorCode":"NOT_AUTHORIZED","errorMessage":"**AppKey is not configured for service**","connectionClosed":true,"connectionId":"..."}

Is that because I do not use a live key?

**Comment by liampauling** [comment]
Yes

**Comment by liampauling** [comment]
Actually I lied, you can get it authorised:

https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/Application+Keys
