### ISSUE TITLE
Matched bets not in order stream

### ISSUE THREAD

**Issue by xgshark** [liampauling/betfair#196]
order_filter = streaming_order_filter(include_overall_position=True)

I only have unmatched bets in the order stream. Is that intended and I have to build a cache and assume that if a bet is no longer in the stream it was matched or am I missing something?

Thanks for any hint.

**Comment by liampauling** [comment]
This is a limitation of streaming for orders.

(Feel free to join the slack group where you will get a response much quicker from the community)

**Comment by xgshark** [comment]
Thanks for adding me to the Slack.

In case someone stumbles upon this - the matched orders are coming through the order stream if they were placed after the stream started.
