### ISSUE TITLE
Betfair API - TLS 1.2 only

### ISSUE THREAD

**Issue by BettingIsCool** [liampauling/betfair#205]
Unfortunately I'm unable to communicate with betfair API.

I received the following mail from the development team

Please be aware that from 7th February, the only protocol for securing the communication between Betfair servers and web browsers at login will be TLS 1.2. Older versions (TLS.1.0, TLS.1.1 or SSLv3) will no longer work.

Although we don't expect this to have an impact on API clients we'd recommend that you refer to the following resources depending on your programming language/framework to confirm that your using TLS 1.2 or above:

Overview of Application’s & Adoption –  https://en.wikipedia.org/wiki/Transport_Layer_Security#Applications_and_adoption

.NET - https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

Java - http://www.ateam-oracle.com/tls-and-java/

PHP - http://php.net/manual/en/migration56.openssl.php

Python - https://docs.python.org/2/library/ssl.html

Would you please be so nice and look into this issue and/or alternatively could let me know how to switch to TLS 1.2

Thank you for your efforts!

**Comment by liampauling** [comment]
This handled by underlying OS / python, what version of python are you using?

https://www.calazan.com/how-to-check-if-your-python-app-supports-tls-12/

**Comment by BettingIsCool** [comment]
Thank you for getting back to me so quickly, really appreciated!

I'm using python 3.7 on windows 10.

Thanx again!
Chris

**Comment by liampauling** [comment]
What do you get when you run that script to tell you your TLS version? Note that I think betfair is down now.

(Feel free to join the slack group where you will get an even quicker reply)

**Comment by BettingIsCool** [comment]
It looks like I'm up to date.

Thank you for pointing out that betfair is down. Then the issue is very likely related to the outage. Sorry for not checking that prior to contacting you.

Many thanx!
Chris
