### ISSUE TITLE
Not aptly named

### ISSUE THREAD

**Issue by 4A47** [liampauling/betfair#210]
Should change name to betfairmoderatelyoverweight

Been trying to find code between the comments, one file had 165 lines of comments in 230 SLOC.

11 defined exceptions, that 6% of the python standard library exceptions. 

Base Class pass... 
class InvalidResponse(BetfairError): "Exception raised if invalid response"

Where did you learn this stuff, school? Must be 1000 lines of pointless comments for self explanatory functions, and its all packed into the documentation as well making it a mega long page with mostly irrelevant info. Written by robots for robots.

Appreciate the effort as the Betfair API is horrendous considering the year, would have been acceptable in 1975, but this is not lightweight.

**Comment by liampauling** [comment]
Hi @4A47,

The 11 defined exceptions all inherit from a single exception, having 11 makes it easier for those new to know what has gone wrong (with over 250 people on the slack group this happens a lot).

As I am sure you learnt in nursery doc strings / comments aren't compiled in python so are only there to help those looking through the code which has been a big positive in getting others to contribute (a lot of first time os contributors, maybe this could be your first?). However most of this code was written over 3 years ago where I was learning about api design and python best practices.

You seem to be overthinking the name, it is referring to its relative speed, before bflw was here the only alternative was this

https://github.com/jmcarp/betfair.py

As you know python is slow however there are things you can do to speed it up; using schematics such as betfair.py does is not one of them, feel free to compare them. 

This library is used by myself and many others (including syndicates and betfair themselves) to handle millions of updates per hour, I think you have missed the point of the name.

**Comment by 4A47** [comment]
Nothing is compiled in python, and I'm probably in a minority of the users looking through the code. Looking at your other smaller projects I prefer but obviously this became more professional with contributers and its high quality, just think there is a lot of needless noise and a touch of over engineering but I'm just an amateur idealist.

Maybe I have missed the intended meaning of lightweight, but maybe it wasn't the best choice if the intended meaning was speed, lightweight to me means minimal.

**Comment by liampauling** [comment]
At runtime python is compiled into bytecode (.pyc files you can see) this is then interpreted, assuming you are using CPython.

I am putting millions of pounds through this library so I want it as over engineered as possible.

To be honest I don't think I have ever seen anyone complain about there being too many docs and the name has always been about speed and offering the functions that a normal user would want in order to make a functional program with the API-NG.

**Comment by 4A47** [comment]
It's an interface to an interface, betfair handles the heavy lifting and ssl the scurity, its a wrapper to presumably improve interacting with the underlying betfair api, you aren't building betfair from scratch.
