### ISSUE TITLE
MarketCatalogueDescription __init__ breaks for imcompletely returned descriptions

### ISSUE THREAD

**Issue by n00bmind** [liampauling/betfair#215]
Hi,
While exploring the returned data for some baseball markets, I started getting this exception:

`TypeError: __init__() missing 7 required positional arguments: 'discountAllowed', 'marketBaseRate', 'persistenceEnabled', 'regulator', 'rules', 'rulesHasDate', and 'wallet'`

which then raises InvalidResponse and prints the whole json returned.
I'm specifying 'MARKET_DESCRIPTION' in my market projection for the listMarketCatalogue request and the returned response does indeed _not_ include the mentioned fields. I checked the docs at https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/Betting+Type+Definitions#BettingTypeDefinitions-MarketDescription and it states that some of those attributes are required, so this is a bit puzzling.

The description only seems incomplete for some markets in the response, not others. I've never seen this error when browsing football markets, also, although admittedly I don't request the description very often.

Any ideas?

**Comment by liampauling** [comment]
This is missing data from betfair, have you raised with them?

**Comment by n00bmind** [comment]
Hi,
No I didn't but I'll try..
Still, I feel the library should be a tad more resilient and not just break down without at least a proper error message about what went wrong, don't you think?

Cheers

**Comment by liampauling** [comment]
Not really sure how that error message could be improved, it tells you what is wrong and what is missing. No library can be 100% resilient to the crap that comes out from Betfair.

PR’s are always welcome...

**Comment by agberk** [comment]
If you set the lightweight option to True you'll get the response as a dict - it won't try to create an object out of it and therefore you won't get exceptions in these cases where the fields marked as required are missing from Betfair.

The keys will of course still be missing from the dict but you can access them with `get` to be defensive in handling missing fields.
