### ISSUE TITLE
BUG: parsing historical data error

### ISSUE THREAD

**Issue by ri938** [liampauling/betfair#216]
The historical data normally parsed OK except for when doing a historical data stream on the file 

2018-02-26 
1.40628214.json

This fails during market_book_cache.create_resource for one of the entries

clk = 6093293715 

with an error about not being able to find a particular runner_id

**Comment by liampauling** [comment]
https://github.com/liampauling/betfair/issues/160

Betfair bug, hasn't been since, wary of hacking a fix.
