### ISSUE TITLE
Is ujson monkey-patch of requests correct?

### ISSUE THREAD

**Issue by synapticarbors** [liampauling/betfair#217]
I was digging around the `requests` code base and noticed that the monkey-patch used here:

https://github.com/liampauling/betfair/blob/master/betfairlightweight/endpoints/baseendpoint.py#L12-L14

appears not to do anything because internally `requests` is using the following import:

```
from .compat import json as complexjson
```

https://github.com/kennethreitz/requests/blob/master/requests/models.py#L42

It seems like this should be:

```
requests.models.complexjson = ujson
```

instead.

**Comment by liampauling** [comment]
Good find.

Going to want to test this as ujson sometimes does some weird things, note how I didn't include it in streaming because it was doing something very odd with decimals.

**Comment by synapticarbors** [comment]
Out of curiosity, can you describe the behaviour you were seeing with regard to decimals? I saw the reversion in the commits, but not a description.

**Comment by liampauling** [comment]
If you monkey patch the listener and run streaming in DEBUG you can see the following:

`betfairlightweight.streaming.listener.json = ujson`

![Screenshot 2019-06-20 at 17 07 42](https://user-images.githubusercontent.com/12016537/59864114-06c13b00-937e-11e9-866b-625cd14eccce.png)

**Comment by synapticarbors** [comment]
And just to be 100% clear, is the issue just the floating point `2.719999999...` instead of presumably `2.72`?

**Comment by liampauling** [comment]
Yes although looking at the docs the following can fix it:

![Screenshot 2019-06-20 at 17 13 32](https://user-images.githubusercontent.com/12016537/59864497-cdd59600-937e-11e9-9941-5e80fa0d332e.png)
