### ISSUE TITLE
Historical File Download - Getting 200 response Error 

### ISSUE THREAD

**Issue by varneyo** [liampauling/betfair#220]
Hi , 

Im seeing strange behaviour when using the method historic.get_my_data().
Some times it will run fine then other times im getting a 200 response error and it will persist. 

Is this something that has been seen before? Is this a betfair or something in the code?

**Comment by liampauling** [comment]
Betfair.

**Comment by varneyo** [comment]
Any more info?

I will contact Neil in the Dev team but it would be nice to have more info on the issue.

Regards, 
Ollie

**Comment by liampauling** [comment]
Its pending a rewrite, its always been crap:

https://forum.developer.betfair.com/forum/developer-program/historical-data/26927-historical-data-data-for-nov-18-to-date-not-available
