### ISSUE TITLE
Issue with in_play_service

### ISSUE THREAD

**Issue by atpapuestas** [liampauling/betfair#221]
Hi, i was using in_play_service.get_event_timeline and suddenly i ve got this error:

 StatusCodeError: Status code error: 503

The line im having problems with is this:

trading.in_play_service.get_event_timeline(event_id=["23423"])

I m workin from Spain so i think this could be part of the problem, but few days in the past i was using this without any problem.

Sorry for my English, hope anyone could help me. Thanks

**Comment by liampauling** [comment]
eventId should be an integer however could be a different issue as in_play_service isn't a public API.

**Comment by liampauling** [comment]
This is actually due to betfair updating the subdomain to ips.
