### ISSUE TITLE
Traded volume issue

### ISSUE THREAD

**Issue by magiclevinho** [liampauling/betfair#222]
Dear Liam,

The live inplay traded volume for runners 1-3 on match odds gives me back 0 for all game and all runners! Could you confirm this issue or am i doing something wrong?

**Comment by liampauling** [comment]
Hey, I would need to see the code / request you are making, I assume you are missing the option asking for traded volume. 

Feel free to post on slack as well as you will get a much quicker response from other users.

**Comment by liampauling** [comment]
Is due to delayed app key.
