### ISSUE TITLE
Betfairlightweight filters market catalogue

### ISSUE THREAD

**Issue by olenton** [liampauling/betfair#245]
Hi.
Sorry for the simple question - new to this and just trying to work my way through to get to grips. I am trying to access the Market Catalogue with Betfairlightweight, the code is...
def test1(): #marketStartTime
    catalogue_filter = betfairlightweight.filters.market_catalogue(market_ids=[1.1637743362],market_name=['1m2fHcap'],market_projection=["MARKET_START_TIME"])
    catalogues = trading.betting.list_market_catalogue(filter=catalogue_filter)
    df = pd.DataFrame({
        'mst': [market_cat_object.market_start_time for market_cat_object in catalogues]
        })
    print(df)

I get an attribute error... module  'betfairlightweight.filters' has no attribute market_catalogue

Thanks in advance

**Comment by liampauling** [comment]
See examples or post on slack group.
