### ISSUE TITLE
Building wheel for ujson (setup.py) error during installation betfairlightweight

### ISSUE THREAD

**Issue by marboe123** [liampauling/betfair#257]
Hi,

I try to install betfairlightweight although I do not succeed. 

OS: Windows 10
Python 3.7.5 in Anaconda navigator environent

I have downloaded Microsoft Visual Studio in several ways although I keep receiving the same errors.

I am not sure if it is due to Microsoft Visual Studio.
I also read this post:
https://github.com/liampauling/betfair/issues/184
Although the error are not only related to ciso8601: it starts with an error for ujson:

The errors I receive are:

`Building wheels for collected packages: ujson, ciso8601
  Building wheel for ujson (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\brs\.conda\envs\betfair test\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\brs\\AppData\\Local\\Temp\\pip-install-rn1n0n9_\\ujson\\setup.py'"'"'; __file__='"'"'C:\\Users\\brs\\AppData\\Local\\Temp\\pip-install-rn1n0n9_\\ujson\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\brs\AppData\Local\Temp\pip-wheel-_54y18s8' --python-tag cp37
       cwd: C:\Users\brs\AppData\Local\Temp\pip-install-rn1n0n9_\ujson\
  Complete output (6 lines):
  Warning: 'classifiers' should be a list, got type 'filter'
  running bdist_wheel
  running build
  running build_ext
  building 'ujson' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for ujson
  Running setup.py clean for ujson
  Building wheel for ciso8601 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\brs\.conda\envs\betfair test\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\brs\\AppData\\Local\\Temp\\pip-install-rn1n0n9_\\ciso8601\\setup.py'"'"'; __file__='"'"'C:\\Users\\brs\\AppData\\Local\\Temp\\pip-install-rn1n0n9_\\ciso8601\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\brs\AppData\Local\Temp\pip-wheel-owpqkedi' --python-tag cp37
       cwd: C:\Users\brs\AppData\Local\Temp\pip-install-rn1n0n9_\ciso8601\
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'ciso8601' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for ciso8601
  Running setup.py clean for ciso8601
Failed to build ujson ciso8601
Installing collected packages: ujson, ciso8601, betfairlightweight
    Running setup.py install for ujson ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\brs\.conda\envs\betfair test\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\brs\\AppData\\Local\\Temp\\pip-install-rn1n0n9_\\ujson\\setup.py'"'"'; __file__='"'"'C:\\Users\\brs\\AppData\\Local\\Temp\\pip-install-rn1n0n9_\\ujson\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\brs\AppData\Local\Temp\pip-record-335uvu8z\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\brs\AppData\Local\Temp\pip-install-rn1n0n9_\ujson\
    Complete output (6 lines):
    Warning: 'classifiers' should be a list, got type 'filter'
    running install
    running build
    running build_ext
    building 'ujson' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\brs\.conda\envs\betfair test\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\boers\\AppData\\Local\\Temp\\pip-install-rn1n0n9_\\ujson\\setup.py'"'"'; __file__='"'"'C:\\Users\\brs\\AppData\\Local\\Temp\\pip-install-rn1n0n9_\\ujson\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\brs\AppData\Local\Temp\pip-record-335uvu8z\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.`

Please help.
Thank you!

**Comment by liampauling** [comment]
Try this

https://github.com/esnme/ultrajson/issues/274

Or install with ignore ujson 

Or buy a Mac

**Comment by marboe123** [comment]
Thanks Liam.

I finally solved the issue. It was due to MS Visual C++ 14.0. After following these steps my issue was solved:

https://www.scivision.co/python-windows-visual-c-14-required/

I have selected Workloads C++ build tools and all three SDK additional install options.
After installing these, I could install betfairlightweight without any issues.

**Comment by liampauling** [comment]
Great, thanks for coming back to reply
