### ISSUE TITLE
PIP install on Windows 10 throws error "Microsoft Visual C++ 14.0 is required"

### ISSUE THREAD

**Issue by ThomasAJ05** [liampauling/betfair#258]
I already have C++ 15.0 installed so I would have thought that would be OK.
Have you harded coded the requirement for C++ V14 or...?

I have the latest PIP and am using Anaconda Prompt > pip install betfairlightweight.

I have attached the error/s.
[CannotInstallBFLight.txt](https://github.com/liampauling/betfair/files/4005340/CannotInstallBFLight.txt)

**Comment by ThomasAJ05** [comment]
SOLVED ...but...possibly/certainly only for Visual Studio users as who the heck wants to download and install Visual Studio just for this dependency. I did try to not use Visual Studio to get "C++ 14.0" but failed.

OK so if you have VS 2019 (and possibly 2017) then Tools > Get Tools and Features... > Workloads > Desktop development with C++ > Optional

**Check** 

> C++/CLI support for v142 build tools

 AND 

> MSVC v140 - VS 2015 C++ build tools (v14.00)

Then **Modify** button in the bottom right hand corner.

I saw similar to this on an MS forum / tried it / and it worked.

**In my OP I said "I already have C++ 15.0 installed" but that was referrig to a REDISTRIBUTABLE package** which I did not realize at the time as I do not code in C++.

It appears this installation needs **...Build Tools...**

So Mr. Pauling could you please be king enough to provide some insight as to why your package specifically needs Build Tools to succesfully install on Windows machines.

I will leave this issue open in the hope you notice it for us non-Pythonistas!

Thank you.

**Comment by liampauling** [comment]
Evening Mr AJ05, this library is optimised for ease of use and speed (I care a lot about the latter) hence the inclusion of ujson and ciso. As mentioned in the following issue you can install without these packages and using some python magic it will still work.

https://github.com/liampauling/betfair/issues/257#issuecomment-569303089

Windows being shit is beyond my scope 😄
