### ISSUE TITLE
can not find Market name "1m4f **Grp 1**" in stream flow using betfairlightweight

### ISSUE THREAD

**Issue by Donjwan80** [liampauling/betfair#259]
Hi, 
I wonder if the market name is captured in the stream data. I need that to know the market class or grade.
"1m4f **Grp 1**"
"1m5f **Cls 1**"

if not what is the best way to get them.

thanks

**Comment by liampauling** [comment]
Market name is only included in historic data, you will need to make a marketCatalogue request and link it up. Feel free to join the slack group for these questions as you will get a quicker and better response 😄 

https://github.com/liampauling/betfair/blob/master/betfairlightweight/resources/streamingresources.py

**Comment by Donjwan80** [comment]
thanks Liam for you reply and for this amazing and elegant software you have created. i actually downloaded the Slack app specifically for this, and tried to join the slack channel but couldnt find it , it asked for workspace which i didnt know

**Comment by liampauling** [comment]
No problem, I think you need to click the link on the readme and it should give you access, as you would expect the workspace is called betfairlightweight.

**Comment by Donjwan80** [comment]
thanks, i joined it now
