### ISSUE TITLE
ConnectTimeoutError not handled correctly, resulting in an AttributeError

### ISSUE THREAD

**Issue by yorickvanzweeden** [liampauling/betfair#280]
In _exceptions.py:105/106_:
```
        if response:
            error_data = response.get("error")
```
This results in an exception on a timeout, as there will be a response but no error. This leads to an Attribute error. `{AttributeError}'str' object has no attribute 'get'`

Example response I encountered:
```
SportsAPING/v1.0/listRunnerBook 
Params: {'marketId': 'someId', 'selectionId': someId, 'priceProjection': someProjection} 
Exception: HTTPSConnectionPool(host='api.betfair.com', port=443): Max retries exceeded with url: /exchange/betting/json-rpc/v1 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc08eaa9280>, 'Connection to api.betfair.com timed out. (connect timeout=3.05)'))
```

I am not sure why I keep receiving a ConnectTimeoutError on listRunnerBook. I did parallel requests (up to 8), which seems non-excessive to me. Any ideas?

**Comment by liampauling** [comment]
Which version are you using? I don't understand how you have managed to get a str passed to that Exception. Can you replicate / show full stack trace?

Not sure how you are handling the session as requests isn't thread safe.

**Comment by yorickvanzweeden** [comment]
Yeh, I was using requests with joblib. I needed to fetch a lot of separate runnerbooks. I switched to aiohttp

**Comment by liampauling** [comment]
No problem, recommend streaming if you are after lots of data quickly and efficiently 👍

**Comment by yorickvanzweeden** [comment]
Thanks for the recommendation! I had not yet considered that, but my workload is more burst like. So I suspect async on multiple cpus is better suited?

**Comment by liampauling** [comment]
With streaming you can have a cache up to date with all the markets you need and then just snap it when you need data. You can run streaming off a single CPU with literally no ram, polling is slower for everything:

https://liampauling.github.io/betfair/streaming/
