### ISSUE TITLE
Markets moved under a new eventId

### ISSUE THREAD

**Issue by benisraelnir** [liampauling/betfair#295]
I think there is an issue with the Stream API when a market moved to a new eventID. 
Today I had an issue with most of horse races @Hanoover when I didn't get updates on the new "version" of the market when I used betfairlightweight stream API to get the data (. (only the old version was retrieved with the first 'img' and no other updates on that market received).  

from Betfair support I have got:
"**Markets moved under a new eventId** - In certain circumstances, a market may move from one eventId to another due to actions performed by the Exchange Operations team.  This will cause the Exchange Stream API to hold two copies of the market in its cache and the initial image of the market provided will therefore contain both copies of the market.  In these circumstances further Stream API updates will only be sent for the latest version of the market.  You can identify the latest version of the market using the "version" parameter returned in the initial image and should only store the market with the higher version number."

**Comment by liampauling** [comment]
Someone on the slack group had an issue with this, for some reason I didn't, do you have a recording of the market streaming data?

**Comment by liampauling** [comment]
Manage to source the market from slack (thanks Mo) and I don't see any issues, as you can see the from the screenshot the market suspends and the eventId gets updated and then becomes active. Did you subscribe to the eventId?

<img width="826" alt="Screenshot 2020-05-08 at 10 05 11" src="https://user-images.githubusercontent.com/12016537/81390464-6a2d9600-9113-11ea-9496-e46d92b61477.png">

**Comment by benisraelnir** [comment]
Nope. I have subscribed with the Market Id.
Will let you know if it happens again

**Comment by liampauling** [comment]
Odd, will close for now.
