### ISSUE TITLE
market_catalogue.runners not pulling data

### ISSUE THREAD

**Issue by 23Steve32** [liampauling/betfair#300]
When I run        
```
 for runner in market_catalogue.runners:
            # prints runner id, runner name and handicap
            print(runner.selection_id, runner.runner_name, runner.handicap)
```
it doesn't return any data. I'm trying for football markets, am I missing something obvious? 

Thanks,
Steve

**Comment by liampauling** [comment]
Are you asking for it in the market_projection?

```python
market_projection = [
    "RUNNER_DESCRIPTION",
]
```

https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/Betting+Enums#BettingEnums-MarketProjection

**Comment by 23Steve32** [comment]
Doh! That would help, thank you :)

**Comment by liampauling** [comment]
👍 feel free to join the slack group btw as you might get a quicker response next time if I am not available.

https://betfairlightweight.herokuapp.com/

**Comment by 23Steve32** [comment]
Will do, thanks again
