### ISSUE TITLE
Exceptions can not be pickled

### ISSUE THREAD

**Issue by aquasync** [liampauling/betfair#312]
I've been using betfairlightweight in conjunction with multiprocessing (via ProcessPoolExecutor), and occasionally an uncaught exception will bubble up to the parent process, usually resulting in:

```
...
  File "/home/test/betfairlightweight/exceptions.py", line 93
    error_data = response.get('error')
AttributeError: 'str' object has no attribute 'get'
```

I just assumed this was some obscure betfairlightweight issue, but turns out the underlying problem is just that the custom exceptions can't be pickled:

```
exc = None
try:
    trading.account.list_currency_rates(from_currency='XYZ')
except Exception as e:
    exc = e

import pickle
pickle.loads(pickle.dumps(exc))
# => AttributeError: 'str' object has no attribute 'get'
```

The current design of all the exception classes is to format a message from arbitrary objects (eg requests response objects etc), but all that gets stored is the final message. You can see some of the possible solutions here - https://stackoverflow.com/questions/16244923/how-to-make-a-custom-exception-class-with-multiple-init-args-pickleable.

I've tended to go the route of passing the unaltered arguments directly to super() so that it can be re-constituted easily:

```
class MyException(Exception):
    def __init__(self, arg1, arg2):
        super(MyException, self).__init__(arg1, arg2)        
        self.arg1 = arg1
        self.arg2 = arg2
```

The message can still be formatted afterwards, and would need a custom `__repr__`, or perhaps just build on the fly in each subclass' `__repr__` method.  An upshot to this is not having to grovel around in the formatted string when more detail is needed.

Alternatively it is possible to address by using a custom `__reduce__` method in the base class, but it needs to do some contortions to avoid calling constructors:

```
class BetfairError:
    def __reduce__(self):
        tup = super(BetfairError, self).__reduce__()
        return (tup[0].__new__, (tup[0],), {'args': tup[1]})
```

Happy to submit a pull request one way or the other - what is your thinking?

**Comment by liampauling** [comment]
Not something I have encountered before but happy to accept a PR on what works best.

**Comment by aquasync** [comment]
Adding `__reduce__` is in some ways the least risky - shouldn't affect anything except the pickle/unpickle use case which didn't work before. 

That said my preference is probably to go the other route as there's times when it's useful to get underlying error data (eg errorCode from a ListenerError etc). I have an except clause currently doing `if 'Exception: ConnectionError' in str(e)` which is icky. That shouldn't be a breaking change in that `str()` and `repr()` will remain the same, there'll just be more some attributes. The only other difference would be that `BetfairError.args` won't contain a tuple with the formatted message. If that's alright I can look to put it together.
