### ISSUE TITLE
"EX_MARKET_DEF" must be requested to use cache

### ISSUE THREAD

**Issue by aquasync** [liampauling/betfair#314]
Recently I've been getting this error sporadically, even though I am include `EX_MARKET_DEF` in my market_data_filter. I haven't actually changed this part of the code, so not sure if perhaps something has changed on betfair's side that doesn't play well with betfairlightweight?

My streaming code is very similar to that from the example, though I'm using multiple streams concurrently to track a large number of markets. It usually works fine, but randomly will throw that error right after starting a subscription.

**Comment by liampauling** [comment]
This is betfair, not much we can do if they don't provide the def.

**Comment by aquasync** [comment]
Is there a way I can just have it ignore the problematic markets? Currently it will resubscribe a few times until it seems to work again for a while, but a lot gets missed that way.

**Comment by liampauling** [comment]
Wait what version are you using?

**Comment by aquasync** [comment]
Ah, sorry I'm on 1.10.0. I read through the changes in preparation for an upgrade but missed that. Indeed looks like the same problem. Thanks!
