### ISSUE TITLE
Unable to retrieve list_event_types

### ISSUE THREAD

**Issue by ChrisQB8** [liampauling/betfair#316]
```
trading = betfairlightweight.APIClient(username, password, key, path)
trading.betting.list_event_types(filter=betfairlightweight.filters.market_filter(text_query='Horse Racing'))
```

returns an empty list since 2 days.

I have successfully used the above script for years without problems.

Has there been any changes?

I'm completely clueless and would appreciate any help or pointers to fix this bug!

**Comment by liampauling** [comment]
Works fine for me, I would check your appKey with bdp

```
{'eventType': {'id': '7', 'name': 'Horse Racing'}, 'marketCount': 568}
```

**Comment by ChrisQB8** [comment]
Hello Liam,

Thank you for your prompt response and your continous support.

You were right that the API is working fine.

It was an issue on my end. Apologies for bothering and opening an issue on github.

Thanx again,
Chris

**Comment by liampauling** [comment]
Np, feel free to join the [slack group](https://betfairlightweight.herokuapp.com/) for an even quicker response next time 👍
