### ISSUE TITLE
Historical Data Example not working

### ISSUE THREAD

**Issue by franz101** [liampauling/betfair#321]
It fetches the file list but then  can not decode the json:

betfairlightweight/endpoints/historic.py in request(self, method, params, session)
    198         try:
--> 199             response_json = json.loads(response.content.decode("utf-8"))
    200         except ValueError:

InvalidResponse: Invalid response received: 

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ngErrorRedirect</title>
</head>
<body>
    <div> 
        Error
    </div>
</body>
</html>

**Comment by franz101** [comment]
Further progress Is made after pruchasing the data now just figuring out how to remove the timeout

**Comment by liampauling** [comment]
If you have any further issues feel free to join the slack group as you will get a much quicker response

**Comment by franz101** [comment]
Thanks very kind

**Comment by Zard44** [comment]
Sorry to re-open this post but i'm having a similar issue, what's the solution?

`{'marketTypesCollection': [{'name': '', 'count': 46}, {'name': 'DAILY_WIN_DIST', 'count': 1}, {'name': 'EACH_WAY', 'count': 23}, {'name': 'FORECAST', 'count': 8}, {'name': 'MATCH_BET', 'count': 25}, {'name': 'OTHER_PLACE', 'count': 110}, {'name': 'PLACE', 'count': 168}, {'name': 'RACE_WIN_DIST', 'count': 3}, {'name': 'REV_FORECAST', 'count': 15}, {'name': 'WIN', 'count': 220}, {'name': 'WITHOUT_FAV', 'count': 2}], 'countriesCollection': [{'name': 'AU', 'count': 151}, {'name': 'CL', 'count': 10}, {'name': 'DE', 'count': 9}, {'name': 'FR', 'count': 17}, {'name': 'GB', 'count': 181}, {'name': 'HK', 'count': 2}, {'name': 'IN', 'count': 110}, {'name': 'NZ', 'count': 13}, {'name': 'US', 'count': 109}, {'name': 'ZA', 'count': 19}], 'fileTypeCollection': [{'name': 'E', 'count': 46}, {'name': 'M', 'count': 575}]}
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
c:\users\a\appdata\local\programs\python\python38-32\lib\site-packages\betfairlightweight\endpoints\historic.py in request(self, method, params, session)
    198         try:
--> 199             response_json = json.loads(response.content.decode("utf-8"))
    200         except ValueError:

c:\users\a\appdata\local\programs\python\python38-32\lib\json\__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    356             parse_constant is None and object_pairs_hook is None and not kw):
--> 357         return _default_decoder.decode(s)
    358     if cls is None:

c:\users\a\appdata\local\programs\python\python38-32\lib\json\decoder.py in decode(self, s, _w)
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()

c:\users\a\appdata\local\programs\python\python38-32\lib\json\decoder.py in raw_decode(self, s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 4 column 1 (char 6)

During handling of the above exception, another exception occurred:

InvalidResponse                           Traceback (most recent call last)
<ipython-input-27-59535749dfa3> in <module>
11
     12 # get advance basket data size
---> 13 basket_size = trading.historic.get_data_size(
     14     "Horse Racing", "Basic Plan", 1, 3, 2017, 1, 3, 2017
     15 )

c:\users\a\appdata\local\programs\python\python38-32\lib\site-packages\betfairlightweight\endpoints\historic.py in get_data_size(self, sport, plan, from_day, from_month, from_year, to_day, to_month, to_year, event_id, event_name, market_types_collection, countries_collection, file_type_collection, session)
    104         params = clean_locals(locals())
    105         method = "GetAdvBasketDataSize"
--> 106         (response, response_json, elapsed_time) = self.request(method, params, session)
    107         return response_json
108

c:\users\a\appdata\local\programs\python\python38-32\lib\site-packages\betfairlightweight\endpoints\historic.py in request(self, method, params, session)
    199             response_json = json.loads(response.content.decode("utf-8"))
    200         except ValueError:
--> 201             raise InvalidResponse(response.text)
202
    203         return response, response_json, elapsed_time

InvalidResponse: Invalid response received:


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ngErrorRedirect</title>
</head>
<body>
    <div>
        Error
    </div>
</body>
</html>
`
