### ISSUE TITLE
Errors with historic data example

### ISSUE THREAD

**Issue by Zard44** [liampauling/betfair#336]
https://github.com/liampauling/betfair/blob/master/examples/examplehistoricdata.py

Firstly thanks for creating and sharing this repo.
I seem to be getting an error in the code which is similar to an issue initially mentioned here:   https://github.com/liampauling/betfair/issues/321

Section of code causing error
`# get file list
file_list = trading.historic.get_file_list(
    "Horse Racing",
    "Basic Plan",
    from_day=1,
    from_month=3,
    from_year=2017,
    to_day=31,
    to_month=3,
    to_year=2017,
    market_types_collection=["WIN"],
    countries_collection=["GB"],
    file_type_collection=["M"],
)
print(file_list)`

Is this a known issue or any suggestions to resolve?
(edited the code slightly for non-cert but i believe the error is unrelated) Thanks again.

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
c:\users\k\appdata\local\programs\python\python38-32\lib\site-packages\betfairlightweight\endpoints\historic.py in request(self, method, params, session)
    198         try:
--> 199             response_json = json.loads(response.content.decode("utf-8"))
    200         except ValueError:

c:\users\k\appdata\local\programs\python\python38-32\lib\json\__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    356             parse_constant is None and object_pairs_hook is None and not kw):
--> 357         return _default_decoder.decode(s)
    358     if cls is None:

c:\users\k\appdata\local\programs\python\python38-32\lib\json\decoder.py in decode(self, s, _w)
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()

c:\users\k\appdata\local\programs\python\python38-32\lib\json\decoder.py in raw_decode(self, s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 4 column 1 (char 6)

During handling of the above exception, another exception occurred:

InvalidResponse                           Traceback (most recent call last)
<ipython-input-13-0ad8a54b4f7a> in <module>
      1 # get file list
----> 2 file_list = trading.historic.get_file_list(
      3     "Horse Racing",
      4     "Basic Plan",
      5     from_day=1,

c:\users\k\appdata\local\programs\python\python38-32\lib\site-packages\betfairlightweight\endpoints\historic.py in get_file_list(self, sport, plan, from_day, from_month, from_year, to_day, to_month, to_year, event_id, event_name, market_types_collection, countries_collection, file_type_collection, session)
    146         params = clean_locals(locals())
    147         method = "DownloadListOfFiles"
--> 148         (response, response_json, elapsed_time) = self.request(method, params, session)
    149         return response_json
    150 

c:\users\k\appdata\local\programs\python\python38-32\lib\site-packages\betfairlightweight\endpoints\historic.py in request(self, method, params, session)
    199             response_json = json.loads(response.content.decode("utf-8"))
    200         except ValueError:
--> 201             raise InvalidResponse(response.text)
    202 
    203         return response, response_json, elapsed_time

InvalidResponse: Invalid response received: 

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ngErrorRedirect</title>
</head>
<body>
    <div> 
        Error
    </div>
</body>
</html>

**Comment by mberk** [comment]
The historic data endpoint is a bit flaky. You might find that running exactly the same code immediately afterwards works fine.

**Comment by Zard44** [comment]
Thanks you're right i ran the script again and it gave me a different error. This time i was able to find the issue. SOLUTION: Need to purchase a data plan on BF for horse racing 2017 before it could progress
