### ISSUE TITLE
Streaming cache memory leak

### ISSUE THREAD

**Issue by liampauling** [liampauling/betfair#340]
Cache leaks memory due to markets/orders not being cleared on closure, more info [here](https://github.com/liampauling/flumine/issues/248).

![Screenshot 2020-10-07 at 08 08 15](https://user-images.githubusercontent.com/12016537/95299268-55e1f680-0875-11eb-8823-8617e43091b3.png)

**Comment by synapticarbors** [comment]
Yeah, I overrode the `_process` method of the `MarketStream` to delete markets 18 hours after their last update and do something similar with the `OrderStream`:

```python
    def _process(self, market_books, publish_time):
        super()._process(market_books, publish_time)

        now = datetime.datetime.utcnow()

        for market_book in market_books:
            mid = market_book['id']
            self.market_last_update[mid] = now

        if (now - self.cache_last_check).total_seconds() > 600:
            for mid in list(self._caches.keys()):
                if (now - self.market_last_update[mid]).total_seconds() > 64800:
                    del self._caches[mid]
                    logger.info('Market {} removed from market cache, {} markets in cache'.format(
                        mid, len(self._caches)))

            self.cache_last_check = now
```

It looks like Flumine is doing something similar as well:

https://github.com/liampauling/flumine/blob/fd26d26947a9cc0ab0f71102f4081415ad5fed4c/flumine/streams/datastream.py#L52-L58

**Comment by liampauling** [comment]
Yeah flumine does it for the data stream but that is only when recording data, anything live isn't, I have a similar idea to above and I think 18-24 hours should reduce the risk to near enough 0.
