### ISSUE TITLE
maturin failed for pip install

### ISSUE THREAD

**Issue by avisionh** [liampauling/betfair#343]
Really sorry if this is a very basic question but I have tried so hard to fix this to no avail.

I've tried to do a simple `pip install betfairlightweight` and received the following error message:

![image](https://user-images.githubusercontent.com/25527485/96194190-c22dbb80-0f41-11eb-890a-e894fab6ff93.png)

I've checked to see if whether `cargo` is in my PATH and it is for my `.profile` and `.zprofile`.

![image](https://user-images.githubusercontent.com/25527485/96194317-0325d000-0f42-11eb-8cf8-abf604eafaf5.png)

Just for extra measure, I checked my system's PATH, which has `cargo` in it:

![image](https://user-images.githubusercontent.com/25527485/96194491-6152b300-0f42-11eb-9065-cf1ea877b803.png)

I've entered `cargo metadata` and got the following error message which might be part of the reason, though I'm not sure how to proceed further (I know 0% Rust and didn't understand most of the Google results).

![image](https://user-images.githubusercontent.com/25527485/96194443-441de480-0f42-11eb-8e0f-4998a595e274.png)

Oh, and `rustc` looks fine on my system?

![image](https://user-images.githubusercontent.com/25527485/96194710-e2aa4580-0f42-11eb-9ec3-093f3c494b2e.png)

 Any pointers will be greatly appreciated. :)

```
macOS Catalina 10.15.7
Python 3.9.0
Shell: zsh
```

Also, installed rustup separately, tested independently and got the same error:
1. The command on the rustup website: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
1. homebrew: `brew install rustup`

**Comment by avisionh** [comment]
Speaking to @arnau, turns out to be the nightly toolchain which I installed via `rustup default nightly`. New issue though. 🙈 

![image](https://user-images.githubusercontent.com/25527485/96276308-b508df00-0fca-11eb-9d0b-b8eb0cf0fb39.png)

**Comment by liampauling** [comment]
Known [orjson](https://github.com/ijl/orjson/issues/136) issue, try 

```bash
pip install betfairlightweight --no-dependencies
```

And then install requests:

```bash
pip install requests<2.25.0

pip install ciso8601==2.1.3
```

**Comment by avisionh** [comment]
Fab, thanks so much @liampauling, that works!
