### ISSUE TITLE
Improve Historic.download_file

### ISSUE THREAD

**Issue by mberk** [liampauling/betfair#345]
`Historic.download_file` currently calls `requests.get` directly:

```python
    def download_file(self, file_path: str, store_directory: str = None) -> str:
        """
        Download a file from betfair historical and store in given directory or current directory.
        :param file_path: the file path as given by get_file_list method.
        :param store_directory: directory path to store data files in.
        :return: name of file.
        """
        local_filename = file_path.split("/")[-1]
        if store_directory:
            local_filename = os.path.join(store_directory, local_filename)
        r = requests.get(
            "%s%s" % (self.url, "DownloadFile"),
            params={"filePath": file_path},
            headers=self.headers,
            stream=True,
        )
        with open(local_filename, "wb") as f:
            for chunk in r.iter_content(chunk_size=1024):
                if chunk:
                    f.write(chunk)
        return local_filename
```

The rest of the methods in this class make use of `Historic.request`, for example:

```python
    def get_my_data(self, session: requests.Session = None) -> dict:
        """
        Returns a list of data descriptions for data which has been purchased by the signed in user.
        :param requests.session session: Requests session object
        :rtype: dict
        """
        params = clean_locals(locals())
        method = "GetMyData"
        (response, response_json, elapsed_time) = self.request(method, params, session)
        return response_json
```

Aside from the obvious disadvantage of code duplication, this means `Historic.download_file` is currently:

1) Not respecting the class's `connect_timeout` and `read_timeout` fields
2) Not taking advantage of the class's `session` field to reuse existing connections to the endpoint which is much more efficient than creating a new connection for each API call

Note that although the implementation currently makes an HTTP GET request and the documentation here: https://historicdata.betfair.com/#/apidocs implies that the GET verb should be used, I have manually tested that the API method works fine when making a POST request with the `filePath` parameter in the POST data instead of the query string.

**Comment by mberk** [comment]
This may simply not be possible. For starters, the response will not be JSON and so it doesn't make sense to try to deserialise it.

It may be that we should just add a `session` argument to `Historic.download_file` and make sure that the call to `requests.get` uses the `connect_timeout` and `read_timeout` fields.

**Comment by liampauling** [comment]
I see, looks like allowing a session var and using the client session would be a good fix.
