### ISSUE TITLE
Socket timeout set after call to connect

### ISSUE THREAD

**Issue by agberk** [liampauling/betfair#396]
The timeout option for the socket is set before the call to `connect` here: https://github.com/liampauling/betfair/blob/master/betfairlightweight/streaming/betfairstream.py#L198-L199

This means the `connect` call could potentially hang indefinitely and not timeout.

I believe we experienced this the other day in our application.

From the Python `socket` docs: https://docs.python.org/3/library/socket.html#timeouts-and-the-connect-method

> The connect() operation is also subject to the timeout setting, and in general it is recommended to call settimeout() before calling connect()

The solution to this would appear to be just to move to the `settimeout` statement before the `connect`.

PR to follow and I'll try to come up with an appropriate test for this.

**Comment by liampauling** [comment]
Any luck? Was going to make a release this week so keen to include if possible.
