### ISSUE TITLE
match_projection

### ISSUE THREAD

**Issue by denilsonc** [liampauling/betfair#415]
param match_projection in list_runner_book is string. is this right?

**Comment by liampauling** [comment]
I believe so https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/Betting+Enums#BettingEnums-MatchProjection

**Comment by denilsonc** [comment]
It seems to me that this returns little runner_book data. how to get Back all and Lay all?

**Comment by liampauling** [comment]
Join the slack group and ask
