### ISSUE TITLE
Retrieving market selection names

### ISSUE THREAD

**Issue by darioscardina** [liampauling/betfair#444]
Hi all,

how can I retrieve "selection name" from selection_id? 
I've seen there is an attribute of RunnerCatalogue called "runner_name". Anyway list_market_catalogue.runners is always an empty list.
Would you be interested in implementing a property of list_market_book.runners for "selection_name"?

Thanks,
Dario

**Comment by liampauling** [comment]
You need to include `RUNNER_DESCRIPTION` in `market_projection` in your request

**Comment by darioscardina** [comment]
Thanks :)
