### ISSUE TITLE
subscribe to both the Market and the Order messages on the same stream

### ISSUE THREAD

**Issue by bensasl2** [liampauling/betfair#447]
hello, 
Can you please double check , I keep getting a confusing error about unique_id when I add both markets and orders to the same stream . 
WARNING:betfairlightweight.streaming.listener:Unwanted data received from uniqueId: 1, expecting: 3

Any help would be much appreciated .

**Comment by liampauling** [comment]
betfairlightweight doesn't handle having both market and order streams through the same socket.

**Comment by bensasl2** [comment]
Thank you very much for your answer. 
I had to run two different streams on two different threads indeed but on the same socket (APICLIENT class)
Thanks

**Comment by liampauling** [comment]
No problem, join the slack group for instant replies 

https://betfairlightweight.herokuapp.com/
